### ISSUE TITLE
Need updated list of DCs for this file

### ISSUE THREAD

**Issue by llundquist** [IBM-Bluemix-Docs/iaas-vpn#1]
We have an angry customer who needs an update for the list of datacenters in this file: 

https://github.com/IBM-Bluemix-Docs/iaas-vpn/blob/master/set-up-pptp-for-osx.md

The customer points out that the Chennai DC is not listed, for one.

Can someone on the engineering or operations side, or the OM side, help us?? ASAP is appreciated.

@lorozco @JillTempelmeyer Can you help me locate the correct person to ask for help?

**Comment by sheltons** [comment]
PPTP has been deprecated and removed. This issue is no longer applicable, so I'm closing it.

**Comment by llundquist** [comment]
Thanks, Susan! This type of issue could arise again, I am not sure. I have no idea how to get updates about (former Softlayer) datacenters. We will cross that bridge if we come to it. As an example, the Direct Link OM team gives regular updates for the docs regarding datacenters available for Direct Link customers.
