### ISSUE TITLE
Use sentence-style caps for topic titles and headings

### ISSUE THREAD

**Issue by cdmauney** [IBM-Bluemix-Docs/iaas-vpn#12]
VPN docs currently use headline-style caps for topic titles and headings. These need to be updated to use sentence-style caps per IBM Cloud content guidelines. 

![image](https://user-images.githubusercontent.com/22623884/45505139-73553c80-b751-11e8-8e69-af3343de0c4d.png)

**Comment by sheltons** [comment]
Fixed in most recent build. Thanks for pointing it out!
