### ISSUE TITLE
SSL VPN for MacOS and Linux

### ISSUE THREAD

**Issue by MHBauer** [IBM-Bluemix-Docs/iaas-vpn#13]
Looking at this page:

https://console.bluemix.net/docs/infrastructure/iaas-vpn/set-up-ssl-vpn-connections.html#set-up-ssl-vpn-connections

No information for MacOS at all, and the linux information references firefox v1.0.4, which is from 2005 if wikipedia is to be believed.

Source is https://github.com/IBM-Bluemix-Docs/iaas-vpn/blob/master/set-up-ssl-vpn-connections.md

**Comment by sheltons** [comment]
This collection is being reviewed as part of a wider Network Core documentation update. We will address your comments there. See the staging repo, issue #64.
