### ISSUE TITLE
SSL VPN Steps need to be updated for cloud.ibm.com

### ISSUE THREAD

**Issue by csciarri** [IBM-Bluemix-Docs/iaas-vpn#19]
The steps for using the SSL VPN need to be updated to reflect the cloud.ibm,com portal.

Manage -> Access (IAM) -> Users (this is a tile).  Select user, then Classic Infrastructure -> VPN subnets.

**Comment by sheltons** [comment]
We've been updating these as we go, and I believe they are all covered now. Thank you for reaching out.
