### ISSUE TITLE
Mac OSX 10.13.3 (17D102) does not have a "pptp" VPN option

### ISSUE THREAD

**Issue by akilunov** [IBM-Bluemix-Docs/iaas-vpn#5]
This document is pretty outdate already - I'm running the latest OS yet I only have 3 options:
1. L2TP over IPSec
2. Cisco IPSec
3. IKEv2

There is no "PPTP" option!

**Comment by jamescooke** [comment]
PPTP will be gone in June anyway: https://console.bluemix.net/docs/infrastructure/iaas-vpn/pptp-deprecation.html#pptp-vpn-deprecation-june-12-2018

**Comment by gdenner** [comment]
Need proper documentation for VPN for SL, unable to gets it working with Cisco IPSec as PPTP instructions don't map and IPSec instructions are not complete.

**Comment by sheltons** [comment]
Thank you for your comments, but PPTP has been deprecated and removed. Closing this ticket.
