### ISSUE TITLE
Add information on using SSL VPN connections without using Java plugins

### ISSUE THREAD

**Issue by jamescooke** [IBM-Bluemix-Docs/iaas-vpn#6]
Since Java plugins have been deprecated for a while (https://www.theverge.com/2016/1/28/10858250/oracle-java-plugin-deprecation-jdk-9) and since the PPTP option will be removed soon (https://console.bluemix.net/docs/infrastructure/iaas-vpn/pptp-deprecation.html#pptp-vpn-deprecation-june-12-2018), please provide new and up to date information on creating VPN connections with SSL without using Java plugins.

For example, using `openvpn` on Ubuntu, I am missing information on where to find a CA certificate for the chosen host in order to create a "password" connection. In addition, settings regarding virtual device type and TCP would be helpful.

**Comment by MHBauer** [comment]
A more standard way to set up the VPN with OS specific items would be nice, especially command line instructions.
Certificate authentication instead of passwords would also be nice.

**Comment by sheltons** [comment]
We are reviewing Network Core collections, and will move this issue into the staging repository for further action. See staging repo issue #65.
