### ISSUE TITLE
Infrastructure: Investigate VPN connection with Ubuntu

### ISSUE THREAD

**Issue by leesakcp** [IBM-Bluemix-Docs/iaas-vpn#7]
@sheltons , I got tapped about a VPN connection issue and, upon further investigation, I believe this content resides in your [About VPN]( https://console.bluemix.net/docs/infrastructure/iaas-vpn/about-vpn.html#about-vpn) infrastructure content.  I created a work item, initially, with the following description:

## Investigate where/how to document VPN connection with Ubuntu

Determine how to handle this.  Is it a one-off? or does it get added?  The DM from Landon Flores:

<img width="721" alt="screen shot 2018-05-15 at 4 36 40 pm" src="https://media.github.ibm.com/user/19361/files/323b7932-585e-11e8-8702-4a1185adfe35">

The follow-up note from Landon:

<img width="1241" alt="screen shot 2018-05-15 at 5 34 32 pm" src="https://user-images.githubusercontent.com/20911005/40084784-48649f7e-5866-11e8-829c-b85bd82affdf.png">

SoftLayer had documented the process:  https://knowledgelayer.softlayer.com/procedure/ssl-vpn-linux

A customer then created their own doc, which, understandably, our support team does not want to point our customers to:  https://www.faridrener.com/2018/04/10/Softlayer-SSL-VPN-Ubuntu.html
Related to [Customer-portal: Investigate addressing holes in VPN information from Usabilla comment](https://github.ibm.com/Bluemix/docs/issues/2543)

Other customers are having trouble with this as well and have opened support tickets:  ttps://internal.softlayer.com/Ticket/ticketPreview/59275105

**Comment by sheltons** [comment]
I'll take a look. Thanks!

**Comment by sheltons** [comment]
The instructions that were in knowledgelayer have been moved over to https://github.ibm.com/Bluemix-Docs/iaas-vpn/blob/staging/standalone-vpn-clients.md, but I do see that the version for MotionPro is old. I'm making a few updates, and will ask for reviews to see if I have all the details.
@llundquist, you may want to have a look at this, too.

**Comment by llundquist** [comment]
I reviewed your PR, LGTM! Thanks!

**Comment by sheltons** [comment]
Pushed in commit b941627. I added portions of the information from the  `faridrener.com` page. Let me know if that's sufficient for the customer's needs, @leesakcp ?

**Comment by sheltons** [comment]
Closing this ticket, as it appears we've addressed the issue.
