### ISSUE TITLE
Infrastructure:  Usabilla suggestions for VPN content

### ISSUE THREAD

**Issue by leesakcp** [IBM-Bluemix-Docs/iaas-vpn#8]
Hi again, @sheltons,  

I had a Usabilla comment awhile back that was asking for more VPN information in my [customer portal](https://console.bluemix.net/docs/customer-portal/getting-started.html#getting-started) content.  I added links from my files to the big section of VPN information that you own to resolve the issue, assuming that it's all probably extremely well documented.  I had also asked the guy who opened the Usabilla issue (Olivier Dupuy d'Uby, an internal IBMer in France) for more information about what he was trying to do and what he was looking for in the information and I'll share his response with you, just in case you see anything you want to add or change in the VPN content.  If not, you can just close this work item but here are his comments...  

Response from [Usabilla issue 2469](https://github.ibm.com/Bluemix/Documentation-content/issues/2469) reporter Olivier Dupuy d'Uby: 

Yes the article you mentioned (https://console.bluemix.net/docs/customer-portal/cpprotectsys.html#cp_bpuseprivnet) points a link where I could find the information. 
However, it is not clear at all... I explain why :

Actually I managed to connect to the VPN last week. I landed on https://www.softlayer.com/vpn-access after a Google search, choosing my nearest DC (Paris) showed me the login portal. There, there is a “help” link on the bottom left referencing a page where the VPN client can be downloaded.

After installing the VPN client, I had to guess the hostname (vpn.par01.softlayer.com) taking the same as the previous login portal address.

To my mind, the documentation could be improved, giving in only one place :
* Explanation of the different networks architectures (private / public) and the possibility to connect to the private using a VPN.
* Explanation on how to enable VPN access to a user.
* Links to download the VPN Client
* Explanation on how to configure the VPN client.

**Comment by sheltons** [comment]
I'm going to copy this over to the staging repo and see if it's something we want to add, or if it's already covered. Closing this ticket.
